# Generated by Django 3.1.3 on 2020-11-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_book_genres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_movie_genres',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_book_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_fav_book', to='categories.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_movie_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_fav_movie', to='categories.category'),
        ),
    ]
