# Generated by Django 3.1.3 on 2020-11-10 10:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_books',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Fantasy'), (2, 'Adventure'), (3, 'Romance'), (4, 'Contemporary'), (5, 'Dystopian'), (6, 'Mystery'), (7, 'Horror'), (8, 'Thriller'), (9, 'Paranormal'), (10, 'Historical fiction'), (11, 'Science Fiction'), (12, 'Memoir'), (13, 'Cooking'), (14, 'Art'), (15, 'Self-help'), (16, 'Development'), (17, 'Motivational'), (18, 'Health'), (19, 'History'), (20, 'Travel'), (21, 'Guide'), (22, 'Families & Relationships'), (23, 'Humor'), (24, 'Children’s')], max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_movies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Comedy'), (4, 'Crime'), (5, 'Drama'), (6, 'Epic'), (7, 'Musical'), (8, 'Science Fiction'), (9, 'War'), (10, 'Westurn')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kr', 'Korean'), ('jp', 'Japanese'), ('cn', 'Chinese')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('mv', 'Movies'), ('bk', 'Books')], max_length=2, null=True),
        ),
    ]
