books = [
    "ABC Bunny",
    "Abraham Lincoln, Friend of the People",
    "Abraham Lincoln's World",
    "Across America on an Emigrant Train",
    "Adventures with Rebbe Mendel",
    "The Alligator's Toothache",
    "Amber Brown",
    "American Girl",
    "Americans Before Columbus",
    "An American Plague",
    "Animal Fairy Tales",
    "The Anubis Tapestry",
    "Arnie the Doughnut",
    "Best Word Book Ever",
    "Better Known as Johnny Appleseed",
    "The Big Tree of Bunlahy",
    "Birthdays of Freedom",
    "Blackout",
    "BLIZZARD! The Storm That Changed America",
    "A Bad Boy Can Be Good For a Girl",
    "Breaking Stalin's Nose",
    "The Bridge to Neverland",
    "Busybody Nora",
    "The Call Of The Wolves",
    "Catwings",
    "CDC?",
    "Cheetah Math",
    "Child of the Wolves",
    "Chrysanthemum",
    "Click, Clack, Moo",
    "Click, Clack, Quackity-Quack",
    "Click, Clack, Splish, Splash",
    "Cloud Boy",
    "Cloudy with a Chance of Meatballs",
    "Computer Engineer Barbie",
    "A Couple of Boys Have the Best Week Ever",
    "The Cow-Tail Switch, and Other West African Stories",
    "Crab Moon",
    "THE CROSSING: How George Washington Saved the American Revolution",
    "Curious George",
    "Curious George Flies a Kite",
    "Curious George Gets a Medal",
    "Curious George Goes to the Hospital",
    "Curious George Learns the Alphabet",
    "Curious George Rides a Bike",
    "Curious George Takes a Job",
    "Curses, Hexes and Spells",
    "A Daughter of the Seine",
    "Davy Crockett",
    "Dear Dumb Diary",
    "Dennis the Wild Bull",
    "Diary of a Spider",
    "Dinosaur vs. Bedtime",
    "Do Unto Otters",
    "Do You Know What I'm Going to Do Next Saturday?",
    "Doctor De Soto",
    "The Dog Who Had Kittens",
    "Dooby Dooby Moo",
    "The Dream Coach",
    "Duck! Rabbit!   ",
    "Gandhi, Fighter Without a Sword",
    "The Gashlycrumb Tinies",
    "George Washington",
    "George Washington's World",
    "Goggles!",
    "The Golden Fleece and the Heroes Who Lived Before Achilles",
    "The Great Fire",
    "The Great Kapok Tree",
    "Green",
    "The Grey Lady and the Strawberry Snatcher",
    "Hachiko Waits",
    "The Happy Hocky Family!",
    "Harry the Dirty Dog",
    "Hattie and the Wild Waves",
    "Have You Seen Tom Thumb?",
    "Heather Has Two Mommies",
    "Heckedy Peg",
    "Help! Mom! There Are Liberals Under My Bed",
    "The Hollow Tree and Deep Woods Book",
    "Hollow Tree Nights and Days",
    "The Hollow Tree Snowed-In Book",
    "How I Learned Geography",
    "Hubert's Hair-Raising Adventure",
    "The Scaredy Cats",
    "Scary Godmother",
    "The Scrambled States of America",
    "The Scrambled States of America Talent Show",
    "Seabird",
    "Seven Little Monsters",
    "The Shrinking of Treehorn",
    "The Sissy Duckling",
    "So You Want to Be President?",
    "Someone Named Eva",
    "Something Queer Is Going On",
    "Spiritual Milk for Boston Babes",
    "Splat the Cat",
    "Splendors and Glooms",
    "Spooky Stories for a Dark and Stormy Night",
    "The Story about Ping",
    "The Story of Appleby Capple",
    "Story of the Negro",
    "Strega Nona",
]