# Generated by Django 3.1.3 on 2020-11-11 11:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField(default=1700, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2020)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('category', models.ManyToManyField(to='categories.Category')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
