# Generated by Django 3.1.3 on 2020-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('books', '0001_initial'),
        ('favs', '0002_auto_20201111_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favlist',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
